apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
spec:
  replicas: 3
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
        - name: helloworld
          image: nabalas/helloworld:c9d75a96268f00c2aabe54cc6e6e0a0fd505831c
          imagePullPolicy: Always
          ports:
            - containerPort: 80
