apiVersion: v1
kind: Service
metadata:
  name: helloworld
spec:
  type: NodePort
  selector:
    app: helloworld
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 31000
